apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  namespace: test-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: myapp-container
          image: hamidiqbal/spring-boot-gitops:latest
          ports:
            - containerPort: 8080
